

base_url = "https://autumnriver.blue"
#theme = "anemone"
minify_html = true
generate_feed = true
default_language = "en"
compile_sass = false

taxonomies = [
    {name = "tags", feed = true},
]

#compile_sass = true

build_search_index = true

[languages.fr]
weight = 2
languageName = "Français"
languageCode = "fr"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
twitter_card = true

favicon = "favicon.ico"
image = ""

default_theme = "light"
list_pages = true


header_nav = [
  { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/blog", name_en = "/blog/", name_fr = "/blog/" },
  { url = "/about", name_en = "/about/", name_fr = "/concernant/" },
  { url = "/now", name_en = "/now/", name_fr = "/now/" },

]
