base_url = "https://autumnriver.blue"
minify_html = true
generate_feed = true
default_language = "en"
compile_sass = false

taxonomies = [
    {name = "tags", feed = true},
]

build_search_index = true

[languages.fr]
weight = 2
languageName = "Français"
languageCode = "fr"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"
generate_toc = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
twitter_card = true
show_thoughts = true
transparent = true
author = "Autumn River"
display_author = true
favicon = "favicon.ico"
image = ""
default_theme = "light"
list_pages = false


header_nav = [
  { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/blog", name_en = "/blog/", name_fr = "/blog/" },
  { url = "/about", name_en = "/about/", name_fr = "/concernant/" },
  { url = "/now", name_en = "/now/", name_fr = "/now/" },

]
